/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 * 	found in "test.asn1"
 * 	`asn1c -S ../../skeletons -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_ATag_H_
#define	_ATag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include "BTag.h"
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ATag__a5 {
	ATag__a5_val1	= 0,
	ATag__a5_val2	= 1,
	ATag__a5_val3	= 2,
	ATag__a5_val4	= 3
} e_ATag__a5;

/* ATag */
typedef struct ATag {
	struct ATag__a1 {
		VisibleString_t	 aa1;
		long	 aa2;
		struct ATag__a1__aa3 {
			long	 aaa1;
			VisibleString_t	 aaa2;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} aa3;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} a1;
	VisibleString_t	 a2;
	BTag_t	 a3;
	struct ATag__a4 {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} a4;
	long	 a5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ATag_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_a5_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ATag;

#ifdef __cplusplus
}
#endif

#endif	/* _ATag_H_ */
#include <asn_internal.h>
