/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 * 	found in "test.asn1"
 * 	`asn1c -S ../../skeletons -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_BTag_H_
#define	_BTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BTag */
typedef VisibleString_t	 BTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BTag;
asn_struct_free_f BTag_free;
asn_struct_print_f BTag_print;
asn_constr_check_f BTag_constraint;
ber_type_decoder_f BTag_decode_ber;
der_type_encoder_f BTag_encode_der;
xer_type_decoder_f BTag_decode_xer;
xer_type_encoder_f BTag_encode_xer;
per_type_decoder_f BTag_decode_uper;
per_type_encoder_f BTag_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BTag_H_ */
#include <asn_internal.h>
