/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 * 	found in "test.asn1"
 * 	`asn1c -S ../../skeletons -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_ETag_H_
#define	_ETag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <VisibleString.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ETag */
typedef struct ETag {
	A_SEQUENCE_OF(struct ETag__Member {
		A_SEQUENCE_OF(struct Member {
			long	 s1;
			VisibleString_t	 s2;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETag;

#ifdef __cplusplus
}
#endif

#endif	/* _ETag_H_ */
#include <asn_internal.h>
