/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "Test"
 * 	found in "test.asn1"
 * 	`asn1c -S ../../skeletons -fcompound-names -gen-PER -pdu=auto`
 */

#ifndef	_HTag_H_
#define	_HTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CTag.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HTag */
typedef CTag_t	 HTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HTag;
asn_struct_free_f HTag_free;
asn_struct_print_f HTag_print;
asn_constr_check_f HTag_constraint;
ber_type_decoder_f HTag_decode_ber;
der_type_encoder_f HTag_encode_der;
xer_type_decoder_f HTag_decode_xer;
xer_type_encoder_f HTag_encode_xer;
per_type_decoder_f HTag_decode_uper;
per_type_encoder_f HTag_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HTag_H_ */
#include <asn_internal.h>
