/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_ATag;
extern struct asn_TYPE_descriptor_s asn_DEF_DTag;
extern struct asn_TYPE_descriptor_s asn_DEF_ETag;
extern struct asn_TYPE_descriptor_s asn_DEF_FTag;
extern struct asn_TYPE_descriptor_s asn_DEF_GTag;
extern struct asn_TYPE_descriptor_s asn_DEF_ITag;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module Test in /Users/shengquangang/Documents/asn-xsd-test/asn/test.asn */
	&asn_DEF_ATag,	
	&asn_DEF_DTag,	
	&asn_DEF_ETag,	
	&asn_DEF_FTag,	
	&asn_DEF_GTag,	
	&asn_DEF_ITag,	
	0
};

